### ISSUE TITLE
word wrap long metric names

### ISSUE THREAD

**Issue by akvadrako** [obfuscurity/tasseo#69]
Metric names can get quite long, and if they contain only dots, letters and numbers will not be wrapped. I have added this custom style and think it would be a good standard addition:

``` css
.overlay-name { font-size: 12pt; word-wrap: break-word; }
```
